escuela/escuela/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

escuela/main/urls.py
from django.conf.urls import url
from . import views
from escuela import settings
from django.contrib.auth import views as auth_views
from django.views import static

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),

    url(r'^equipo/list/$', views.EquipoListView.as_view(), name='equipo_list'),
    url(r'^equipo/(?P<pk>[0-9]+)/$', views.EquipoDetailView.as_view(), name='equipo_detail'),
    url(r'^equipo/add/$', views.EquipoCreateView.as_view(), name='equipo_add'),

    url(r'^alumno/(?P<pk>[0-9]+)/$', views.AlumnoDetailView.as_view(), name='alumno_detail_'),
    url(r'^alumno/(?P<pk>[0-9]+)/mensaje$', views.MensajeCreateView.as_view(), name='mensaje_add_'),
    url(r'^alumno/add/$', views.AlumnoCreateView.as_view(), name='alumno_add'),

    url(r'^reto/list/$', views.RetoListView.as_view(), name='reto_list'),
    url(r'^reto/add/$', views.RetoCreateView.as_view(), name='reto_add'),
    url(r'^reto/(?P<pk>[0-9]+)/$', views.RetoDetailView.as_view(), name='reto_detail'),
    url(r'^reto/materia/$', views.MateriaCreateView.as_view(), name='materia_add'),

    url(r'^n/add/$', views.NotaFormView.as_view(), name='nota_add'),

    url(r'^p/add$', views.UserFormView.as_view(), name='profile_add'),
    url(r'^p/inbox$', views.PostAlumnoList.as_view(), name='inbox'),
    url(r'^p/mensaje/(?P<pk>[0-9]+)/$', views.PostAlumnoDetail.as_view(), name='mensaje_detail_'),

    url(r'^perfil/(?P<pk>[0-9]+)/$', views.PerfilDetailView.as_view(), name='perfil_detail'),
    url(r'^perfil/(?P<pk>[0-9]+)/edit$', views.PerfilUpdateView.as_view(), name='perfil_update'),
    url(r'^perfil/add/$', views.PerfilCrearView.as_view(), name='perfil_add'),

    url(r'^mensaje/(?P<perfil_id>[0-9]+)/$', views.MensajeDetailView.as_view(), name='mensaje_detail'),

    url(r'^store/$', views.StoreView.as_view(), name='store'),
    url(r'^store/compra$', views.CompraCreateView.as_view(), name='compra_create'),

    url(r'^apoyar/(?P<nota_id>[0-9]+)/$', views.ApuestaCreateView.as_view(), name='apuesta_create'),

    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name="login"),
    url('^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),

    url(r'^password_change/$', views.password_change, name='password_change'),

    #url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'user/password_reset.html', 'post_reset_redirect': '/'}, name="password_reset"),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),

    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})
]

escuela/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
from django.utils import timezone
from easy_thumbnails.fields import ThumbnailerImageField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    public = models.BooleanField(default=False)
    es_jugador = models.BooleanField(default=True)
    foto = ThumbnailerImageField(
        upload_to="perfil_usuario",
        null=True,
        blank=True,
        editable=True,)
    portada = ThumbnailerImageField(
        upload_to="portada_usuario",
        null=True,
        blank=True,
        editable=True,
        help_text="Portada de usuario",
        verbose_name="Portada de usuario")

    def tokens_activos(self, fecha=date.today()):
        tokens = 0
        tokens_compra = sum(c.paquete.tokens for c in self.compras.all())
        tokens_apuesta = sum(a.tokens for a in self.apuestas.all())
        return tokens + tokens_compra - tokens_apuesta

    def get_puntos(self, fecha=date.today()):
        puntos = 0
        apuestas = self.apuestas.filter(nota__reto__fecha__lt=fecha)
        return sum(a.get_punteo('int') for a in apuestas)
    puntos = property(get_puntos)

    def get_lugar(self, fecha=date.today()):
        profile_list = Profile.objects.all()
        lugar = profile_list.count() + 1
        for p in profile_list:
            if self.get_puntos(fecha) >= p.get_puntos(fecha):
                lugar = lugar - 1
        return lugar

    def get_inbox(self):
        lista = PostAlumno.objects.filter(para=self, visto=False)
        return lista.count()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    def get_absolute_url(self):
        return reverse('perfil_detail', kwargs={'pk': self.id})


class Paquete(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=7, decimal_places=2)
    tokens = models.IntegerField()
    disponible = models.BooleanField(default=False)
    regalo = models.BooleanField(default=False)
    imagen = ThumbnailerImageField(
        upload_to="imagen_paquete",
        null=True,
        blank=True,
        editable=True,
        help_text="Imagen de paquete",
        verbose_name="Imagen de paquete")

    def __str__(self):
        return self.nombre


class TipoTarjeta(models.Model):
    tipo_tarjeta = models.SlugField(max_length=25)
    alias = models.CharField(max_length=25)

    def __str__(self):
        return self.alias


class Compra(models.Model):
    profile = models.ForeignKey('Profile', related_name='compras')
    paquete = models.ForeignKey('Paquete', related_name='compras_anteriores')
    fecha = models.DateTimeField(default=timezone.now)
    tipo_tarjeta = models.ForeignKey(TipoTarjeta, on_delete=models.PROTECT, null=True, blank=True)
    payment_ref = models.CharField(max_length=225, null=True, blank=True)

    def __str__(self):
        return str(self.paquete) + " de " + str(self.profile)


class Equipo(models.Model):
    nombre = models.CharField(max_length=100)
    logo = ThumbnailerImageField(
        upload_to="equipo_logo",
        null=True,
        blank=True,
        editable=True,
        help_text="Logo de equipo",
        verbose_name="Logo de equipo")
    portada = ThumbnailerImageField(
        upload_to="equipo_portada",
        null=True,
        blank=True,
        editable=True,
        help_text="Portada de equipo",
        verbose_name="Portada de equipo")
    descripcion = models.TextField(null=True)

    def get_promedio(self, fecha=date.today()):
        total = 0
        alumno_lista = Alumno.objects.filter(equipo=self)
        for a in alumno_lista:
            total = total + a.promedio(fecha)
        return total / alumno_lista.count() if alumno_lista.count() > 0 else 0
    promedio = property(get_promedio)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('equipo_detail', kwargs={'pk': self.id})


class Grado(models.Model):
    numero = models.IntegerField()
    seccion = models.CharField(max_length=2, null=True, blank=True)

    def __str__(self):
        return str(self.numero) + " " + self.seccion


class Alumno(models.Model):
    nombre = models.CharField(max_length=150, default='')
    apellido = models.CharField(max_length=150, default='')
    equipo = models.ForeignKey('Equipo', related_name='alumnos')
    foto = ThumbnailerImageField(
        upload_to="perfil_alumno",
        null=True,
        blank=True,
        editable=True,)
    grado = models.ForeignKey('Grado', null=True, blank=True)
    animal = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    sueno = models.CharField(max_length=70, null=True, blank=True)
    juego = models.CharField(max_length=70, null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)

    def promedio(self, fecha=date.today()):
        reto_list = Reto.objects.filter(fecha__lte=fecha)
        nota_list = Nota.objects.filter(alumno=self, reto__in=reto_list)
        total = 0
        for n in nota_list:
            total = total + n.nota
        return total / nota_list.count() if nota_list.count() > 0 else 0

    def blog(self):
        post_lista_all = PostAlumno.objects.filter(alumno=self).order_by('fecha')[:10]
        post_lista = reversed(post_lista_all)
        return post_lista

    def __str__(self):
        return (self.nombre) + " " + self.apellido

    def get_absolute_url(self):
        return reverse('alumno_detail_', kwargs={'pk': self.id})


class Materia(models.Model):
    nombre = models.CharField(max_length=100)
    bg = ThumbnailerImageField(
        upload_to="materia_media",
        null=True,
        blank=True,
        editable=True,)
    icon = ThumbnailerImageField(
        upload_to="materia_media",
        null=True,
        blank=True,
        editable=True,)

    def __str__(self):
        return self.nombre


class Reto(models.Model):
    materia = models.ForeignKey('Materia')
    fecha = models.DateField(unique=True)
    pt_1 = models.IntegerField()
    pt_2 = models.IntegerField()
    pt_3 = models.IntegerField()

    def puntos_profile(self, user):
        puntos = 0
        nota_list = Nota.objects.filter(reto=self)
        for apuesta in Apuesta.objects.filter(user=user, nota__in=nota_list):
            if is_number(apuesta.get_punteo()):
                puntos = puntos + apuesta.get_punteo()
        return puntos

    def __str__(self):
        return str(self.materia) + " en " + str(self.fecha)

    def get_absolute_url(self):
        return reverse('reto_detail', kwargs={'pk': self.id})

    def jugado(self):
        return self.fecha < date.today()

    def ganador(self):
        return self.notas.all().order_by('nota')[0]


class Nota(models.Model):
    alumno = models.ForeignKey('Alumno')
    reto = models.ForeignKey('Reto', related_name='notas')
    nota = models.IntegerField()

    objects = models.Manager()

    class Meta:
        unique_together = ('alumno', 'reto')

    def lugar(self):
        lugar = 1
        list_nota = Nota.objects.filter(reto=self.reto)
        for i in list_nota:
            if self.nota < i.nota:
                lugar = lugar + 1
        return lugar

    def get_nota(self):
        if self.reto.fecha <= date.today():
            return self.nota
        else:
            return '?'

    def get_lugar(self):
        if self.reto.fecha <= date.today():
            return self.lugar()
        else:
            return '?'

    def puntos_token(self):
        if self.lugar() == 1:
            return self.reto.pt_1
        if self.lugar() == 2:
            return self.reto.pt_2
        if self.lugar() == 3:
            return self.reto.pt_3
        return 0

    def get_puntos_token(self):
        if self.reto.fecha <= date.today():
            return self.puntos_token()
        else:
            return '?'

    def __unicode__(self):
        return u'{0}'.format(self.nota)

    def __str__(self):
        return str(self.alumno) + " " + str(self.nota) + " para " + str(self.reto)


class Apuesta(models.Model):
    user = models.ForeignKey('Profile', related_name='apuestas')
    nota = models.ForeignKey('Nota')
    tokens = models.IntegerField()
    fecha = models.DateField(default=timezone.now)

    def punteo(self):
        return self.tokens * self.nota.puntos_token()

    def get_punteo(self, tipo='string'):
        if self.nota.reto.fecha < date.today():
            return self.punteo()
        else:
            return '?' if tipo == 'string' else 0

    def __str__(self):
        return str(self.user) + " para " + str(self.nota)


class PostCategoria(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre


class Post(models.Model):
    titulo = models.CharField(max_length=150)
    fecha = models.DateField(default=timezone.now)
    cuerpo = models.TextField()
    escrito_por = models.ForeignKey('Profile')
    imagen = ThumbnailerImageField(
        upload_to="imagen_mensaje",
        null=True,
        blank=True,
        editable=True,)

    def __str__(self):
        return self.titulo

    def resumen(self):
        return self.cuerpo[:25] + "..."


class PostAlumno(Post):
    alumno = models.ForeignKey('Alumno')
    categoria = models.ForeignKey('PostCategoria', null=True, blank=True)
    para = models.ForeignKey(Profile, related_name='mensajes')
    visto = models.BooleanField(default=False, blank=True)

    def get_absolute_url(self):
        return reverse('mensaje_detail_', kwargs={'pk': self.id})


class Mensaje(Post):
    cobrado = models.BooleanField(default=True)
    para = models.ForeignKey(Alumno)

    def get_absolute_url(self):
        return reverse('alumno_detail_', kwargs={'pk': self.para.id})

escuela/main/templates/store/index.html
{% extends "base/base.html" %}
{% load thumbnail %}
{% block content %}
<div class="container">	
	<div class="row">
		<div class="col-md-9">
			<!-- Pricing Tables -->
			<h2 class="h1">Paquetes disponibles</h2>
			<div class="row vertical-gutter">
				{% for paquete in paquete_lista %}
				<div class="angled-img col-md-3">
					<form action="/compra/" method="POST" data-tokens="{{paquete.paquete.tokens}}" data-precio="{{paquete.paquete.precio}}" class="form-compra">
						<div class="img img-offset">
							<img src="{{ paquete.paquete.imagen|thumbnail_url:'avatar-lg' }}" alt="">
						</div>
						<ul class="pricing-table">
							<li class="plan-name">
								{{ paquete.paquete.nombre }}
							</li>
							<li class="plan-price">
								{{ paquete.paquete.tokens }} tokens
							</li>
							<li>$ {{ paquete.paquete.precio }}</li>
							<li class="plan-action">
								{% csrf_token %}
								{{ paquete.form.paquete }} <button type="submit" value="Comprar" class="btn btn-primary" data-toggle="confirmation">Donar</button>
							</li>
						</ul>
					</form>
				</div>
				{% endfor %}
			</div>
			<!-- /Pricing Tables -->
		</div>
		<div class="col-md-3">
			Actualmente tienes:
			<br>
			<div class="tokens-activos lead">{{ profile.tokens_activos }} tokens válidos</div>
		</div>
	</div>
</div>
{% endblock content %}

escuela/main/templates/store/store.html
{% extends "base/base.html" %}

{% load thumbnail %}

{% block content %}
<div class="container">
	<div class="row">
	<h1  class="colorV" align="right">Tokens Disponibles: {{ user.perfil.tokens_activos }}</h1>
		<div class="col-md-12">
			<div class="row">
			{% for paquete in paquete_list %}
				<div class="col-sm-4 col-lg-4 col-md-4">
					<div class="thumbnail">
						<img src="{{ paquete.imagen|thumbnail_url:"paquete-store" }}" alt="">
						<div class="caption">
							<h4 class="pull-right">${{ paquete.precio }}</h4>
							<h4><a href="#">{{ paquete.tokens }} Tokens Pack</a>
							</h4>
							<p>Apoya a los niños con {{ paquete.tokens }} Tokens</p>

							<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Compra" data-whatever="{{ paquete.precio }}" data-paquete="{{ paquete.id }}">Comprar</button>
						</div>
						<div class="ratings">
							<p class="pull-right">{{ paquete.compras_anteriores.count }} compras por todos</p>
						</div>
					</div>
				</div>
			{% endfor %}
			</div>
		</div>
	</div>
</div>
<!-- /.container -->

<div class="modal fade" id="Compra" tabindex="-1" role="dialog" aria-labelledby="CompraLabel">
	<form action="{% url 'compra_create' %}" method="post">
		{% csrf_token %}
		{{ pago_form.paquete }}
		<div class="modal-dialog" role="document">
			<div class="modal-content credit-card-div">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="CompraLabel">Compra de Paquete</h4>
				</div>

				<div class="modal-body1">
					<div class="credit-card-div">
						<div class="panel panel-default">
							<div class="panel-heading">
								<div class="row">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<h5 class="text-muted"> Número de Tarjeta de Crédito</h5>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										{{ pago_form.number.errors }}
										{{ pago_form.number }}
									</div>
								</div>
								<div class="row ">
									<div class="col-md-3 col-sm-3 col-xs-3">
										<span class="help-block text-muted small-font"> Expira - Mes</span>
										{{ pago_form.expire_month.errors }}
										{{ pago_form.expire_month }}
									</div>
									<div class="col-md-3 col-sm-3 col-xs-3">
										<span class="help-block text-muted small-font">  Expira - Año</span>
										{{ pago_form.expire_year.errors }}
										{{ pago_form.expire_year }}
									</div>
									<div class="col-md-3 col-sm-3 col-xs-3">
										<span class="help-block text-muted small-font">  CCV</span>
										{{ pago_form.cvv2.errors }}
										{{ pago_form.cvv2 }}
									</div>
									<div class="col-md-3 col-sm-3 col-xs-3">
										<span class="help-block text-muted small-font">  Tipo de tarjeta</span>
										{{ pago_form.card_type.errors }}
										{{ pago_form.card_type }}
									</div>
								</div>
								<div class="row">
									<div class="col-md-6 col-sm-6 col-xs-6">
										<span class="help-block text-muted small-font">Nombre en tarjeta</span>
										{{ pago_form.first_name.errors }}
										{{ pago_form.first_name }}
									</div>
									<div class="col-md-6 col-sm-6 col-xs-6">
										<span class="help-block text-muted small-font">Apellido en tarjeta</span>
										{{ pago_form.last_name.errors }}
										{{ pago_form.last_name }}
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- CREDIT CARD DIV END -->

				</div>

				<div class="modal-body2">
					{{ pago_form.non_field_errors }}
					<div class="row credit-card-div">
						<div class="col-md-12 pad-adjust">
						</div>
					</div>
				</div>

				<div class="modal-footer">
					<div class="row ">
						<div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
							<input type="submit" class="btn btn-danger "data-dismiss="modal" value="Cancelar" />
						</div>
						<div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
							<input type="submit" class="btn btn-success btn-block" value="Pagar Ahora" />
						</div>
					</div>
				</div>

			</div>
		</div>
	</form>
</div>

{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
	{% if pago_form.non_field_errors %}	
	$('#Compra').modal('show');
	{% endif %}

	$('#Compra').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget)
		var recipient = button.data('whatever')
		var modal = $(this)
		modal.find('.modal-title').text('Compra de Paquete por: ' + recipient);
		$('#id_paquete').val(button.data('paquete'));
	});
</script>
{% endblock extra_js %}