escuela/escuela/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

escuela/main/urls.py
from django.conf.urls import url
from . import views
from escuela import settings
from django.contrib.auth import views as auth_views
from django.views import static

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),

    url(r'^equipo/list/$', views.EquipoListView.as_view(), name='equipo_list'),
    url(r'^equipo/(?P<pk>[0-9]+)/$', views.EquipoDetailView.as_view(), name='equipo_detail'),
    url(r'^equipo/add/$', views.EquipoCreateView.as_view(), name='equipo_add'),

    url(r'^alumno/(?P<pk>[0-9]+)/$', views.AlumnoDetailView.as_view(), name='alumno_detail_'),
    url(r'^alumno/(?P<pk>[0-9]+)/mensaje$', views.MensajeCreateView.as_view(), name='mensaje_add_'),
    url(r'^alumno/add/$', views.AlumnoCreateView.as_view(), name='alumno_add'),

    url(r'^reto/list/$', views.RetoListView.as_view(), name='reto_list'),
    url(r'^reto/add/$', views.RetoCreateView.as_view(), name='reto_add'),
    url(r'^reto/(?P<pk>[0-9]+)/$', views.RetoDetailView.as_view(), name='reto_detail'),
    url(r'^reto/materia/$', views.MateriaCreateView.as_view(), name='materia_add'),

    url(r'^n/add/$', views.NotaFormView.as_view(), name='nota_add'),

    url(r'^p/add$', views.UserFormView.as_view(), name='profile_add'),
    url(r'^p/inbox$', views.PostAlumnoList.as_view(), name='inbox'),
    url(r'^p/mensaje/(?P<pk>[0-9]+)/$', views.PostAlumnoDetail.as_view(), name='mensaje_detail_'),

    url(r'^perfil/(?P<pk>[0-9]+)/$', views.PerfilDetailView.as_view(), name='perfil_detail'),
    url(r'^perfil/(?P<pk>[0-9]+)/edit$', views.PerfilUpdateView.as_view(), name='perfil_update'),
    url(r'^perfil/add/$', views.PerfilCrearView.as_view(), name='perfil_add'),

    url(r'^mensaje/(?P<perfil_id>[0-9]+)/$', views.MensajeDetailView.as_view(), name='mensaje_detail'),

    url(r'^store/$', views.StoreView.as_view(), name='store'),
    url(r'^store/compra$', views.CompraCreateView.as_view(), name='compra_create'),

    url(r'^apoyar/(?P<nota_id>[0-9]+)/$', views.ApuestaCreateView.as_view(), name='apuesta_create'),

    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name="login"),
    url('^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),

    url(r'^password_change/$', views.password_change, name='password_change'),

    #url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'user/password_reset.html', 'post_reset_redirect': '/'}, name="password_reset"),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),

    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})
]

escuela/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
from django.utils import timezone
from easy_thumbnails.fields import ThumbnailerImageField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    public = models.BooleanField(default=False)
    es_jugador = models.BooleanField(default=True)
    foto = ThumbnailerImageField(
        upload_to="perfil_usuario",
        null=True,
        blank=True,
        editable=True,)
    portada = ThumbnailerImageField(
        upload_to="portada_usuario",
        null=True,
        blank=True,
        editable=True,
        help_text="Portada de usuario",
        verbose_name="Portada de usuario")

    def tokens_activos(self, fecha=date.today()):
        tokens = 0
        tokens_compra = sum(c.paquete.tokens for c in self.compras.all())
        tokens_apuesta = sum(a.tokens for a in self.apuestas.all())
        return tokens + tokens_compra - tokens_apuesta

    def get_puntos(self, fecha=date.today()):
        puntos = 0
        apuestas = self.apuestas.filter(nota__reto__fecha__lt=fecha)
        return sum(a.get_punteo('int') for a in apuestas)
    puntos = property(get_puntos)

    def get_lugar(self, fecha=date.today()):
        profile_list = Profile.objects.all()
        lugar = profile_list.count() + 1
        for p in profile_list:
            if self.get_puntos(fecha) >= p.get_puntos(fecha):
                lugar = lugar - 1
        return lugar

    def get_inbox(self):
        lista = PostAlumno.objects.filter(para=self, visto=False)
        return lista.count()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    def get_absolute_url(self):
        return reverse('perfil_detail', kwargs={'pk': self.id})


class Paquete(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=7, decimal_places=2)
    tokens = models.IntegerField()
    disponible = models.BooleanField(default=False)
    regalo = models.BooleanField(default=False)
    imagen = ThumbnailerImageField(
        upload_to="imagen_paquete",
        null=True,
        blank=True,
        editable=True,
        help_text="Imagen de paquete",
        verbose_name="Imagen de paquete")

    def __str__(self):
        return self.nombre


class TipoTarjeta(models.Model):
    tipo_tarjeta = models.SlugField(max_length=25)
    alias = models.CharField(max_length=25)

    def __str__(self):
        return self.alias


class Compra(models.Model):
    profile = models.ForeignKey('Profile', related_name='compras')
    paquete = models.ForeignKey('Paquete', related_name='compras_anteriores')
    fecha = models.DateTimeField(default=timezone.now)
    tipo_tarjeta = models.ForeignKey(TipoTarjeta, on_delete=models.PROTECT, null=True, blank=True)
    payment_ref = models.CharField(max_length=225, null=True, blank=True)

    def __str__(self):
        return str(self.paquete) + " de " + str(self.profile)


class Equipo(models.Model):
    nombre = models.CharField(max_length=100)
    logo = ThumbnailerImageField(
        upload_to="equipo_logo",
        null=True,
        blank=True,
        editable=True,
        help_text="Logo de equipo",
        verbose_name="Logo de equipo")
    portada = ThumbnailerImageField(
        upload_to="equipo_portada",
        null=True,
        blank=True,
        editable=True,
        help_text="Portada de equipo",
        verbose_name="Portada de equipo")
    descripcion = models.TextField(null=True)

    def get_promedio(self, fecha=date.today()):
        total = 0
        alumno_lista = Alumno.objects.filter(equipo=self)
        for a in alumno_lista:
            total = total + a.promedio(fecha)
        return total / alumno_lista.count() if alumno_lista.count() > 0 else 0
    promedio = property(get_promedio)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('equipo_detail', kwargs={'pk': self.id})


class Grado(models.Model):
    numero = models.IntegerField()
    seccion = models.CharField(max_length=2, null=True, blank=True)

    def __str__(self):
        return str(self.numero) + " " + self.seccion


class Alumno(models.Model):
    nombre = models.CharField(max_length=150, default='')
    apellido = models.CharField(max_length=150, default='')
    equipo = models.ForeignKey('Equipo', related_name='alumnos')
    foto = ThumbnailerImageField(
        upload_to="perfil_alumno",
        null=True,
        blank=True,
        editable=True,)
    grado = models.ForeignKey('Grado', null=True, blank=True)
    animal = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    sueno = models.CharField(max_length=70, null=True, blank=True)
    juego = models.CharField(max_length=70, null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)

    def promedio(self, fecha=date.today()):
        reto_list = Reto.objects.filter(fecha__lte=fecha)
        nota_list = Nota.objects.filter(alumno=self, reto__in=reto_list)
        total = 0
        for n in nota_list:
            total = total + n.nota
        return total / nota_list.count() if nota_list.count() > 0 else 0

    def blog(self):
        post_lista_all = PostAlumno.objects.filter(alumno=self).order_by('fecha')[:10]
        post_lista = reversed(post_lista_all)
        return post_lista

    def __str__(self):
        return (self.nombre) + " " + self.apellido

    def get_absolute_url(self):
        return reverse('alumno_detail_', kwargs={'pk': self.id})


class Materia(models.Model):
    nombre = models.CharField(max_length=100)
    bg = ThumbnailerImageField(
        upload_to="materia_media",
        null=True,
        blank=True,
        editable=True,)
    icon = ThumbnailerImageField(
        upload_to="materia_media",
        null=True,
        blank=True,
        editable=True,)

    def __str__(self):
        return self.nombre


class Reto(models.Model):
    materia = models.ForeignKey('Materia')
    fecha = models.DateField(unique=True)
    pt_1 = models.IntegerField()
    pt_2 = models.IntegerField()
    pt_3 = models.IntegerField()

    def puntos_profile(self, user):
        puntos = 0
        nota_list = Nota.objects.filter(reto=self)
        for apuesta in Apuesta.objects.filter(user=user, nota__in=nota_list):
            if is_number(apuesta.get_punteo()):
                puntos = puntos + apuesta.get_punteo()
        return puntos

    def __str__(self):
        return str(self.materia) + " en " + str(self.fecha)

    def get_absolute_url(self):
        return reverse('reto_detail', kwargs={'pk': self.id})

    def jugado(self):
        return self.fecha < date.today()

    def ganador(self):
        return self.notas.all().order_by('nota')[0]


class Nota(models.Model):
    alumno = models.ForeignKey('Alumno')
    reto = models.ForeignKey('Reto', related_name='notas')
    nota = models.IntegerField()

    objects = models.Manager()

    class Meta:
        unique_together = ('alumno', 'reto')

    def lugar(self):
        lugar = 1
        list_nota = Nota.objects.filter(reto=self.reto)
        for i in list_nota:
            if self.nota < i.nota:
                lugar = lugar + 1
        return lugar

    def get_nota(self):
        if self.reto.fecha <= date.today():
            return self.nota
        else:
            return '?'

    def get_lugar(self):
        if self.reto.fecha <= date.today():
            return self.lugar()
        else:
            return '?'

    def puntos_token(self):
        if self.lugar() == 1:
            return self.reto.pt_1
        if self.lugar() == 2:
            return self.reto.pt_2
        if self.lugar() == 3:
            return self.reto.pt_3
        return 0

    def get_puntos_token(self):
        if self.reto.fecha <= date.today():
            return self.puntos_token()
        else:
            return '?'

    def __unicode__(self):
        return u'{0}'.format(self.nota)

    def __str__(self):
        return str(self.alumno) + " " + str(self.nota) + " para " + str(self.reto)


class Apuesta(models.Model):
    user = models.ForeignKey('Profile', related_name='apuestas')
    nota = models.ForeignKey('Nota')
    tokens = models.IntegerField()
    fecha = models.DateField(default=timezone.now)

    def punteo(self):
        return self.tokens * self.nota.puntos_token()

    def get_punteo(self, tipo='string'):
        if self.nota.reto.fecha < date.today():
            return self.punteo()
        else:
            return '?' if tipo == 'string' else 0

    def __str__(self):
        return str(self.user) + " para " + str(self.nota)


class PostCategoria(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre


class Post(models.Model):
    titulo = models.CharField(max_length=150)
    fecha = models.DateField(default=timezone.now)
    cuerpo = models.TextField()
    escrito_por = models.ForeignKey('Profile')
    imagen = ThumbnailerImageField(
        upload_to="imagen_mensaje",
        null=True,
        blank=True,
        editable=True,)

    def __str__(self):
        return self.titulo

    def resumen(self):
        return self.cuerpo[:25] + "..."


class PostAlumno(Post):
    alumno = models.ForeignKey('Alumno')
    categoria = models.ForeignKey('PostCategoria', null=True, blank=True)
    para = models.ForeignKey(Profile, related_name='mensajes')
    visto = models.BooleanField(default=False, blank=True)

    def get_absolute_url(self):
        return reverse('mensaje_detail_', kwargs={'pk': self.id})


class Mensaje(Post):
    cobrado = models.BooleanField(default=True)
    para = models.ForeignKey(Alumno)

    def get_absolute_url(self):
        return reverse('alumno_detail_', kwargs={'pk': self.para.id})

escuela/main/templates/reto/all.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load index %}
{% block content %}
<section class="content-wrap container">

	<!-- Lista retos -->
	<h2 class="container h1">Retos</h2>
	<section class="youplay-news container">
		<div class="row">
			<div class="col-md-12">
				{% for reto in reto_list %}
				<!-- Bloque reto -->
				<div class="news-one">
					<div class="row vertical-gutter">
						<div class="col-md-4">
							<a href="{% url "reto_detail" id_reto=reto.reto.id %}" class="angled-img">
								<div class="img">
									<img src="{{ reto.ganador.foto|thumbnail_url:'avatar-lg'}}" alt="{{ reto.ganador }}">
								</div>
							</a>
						</div>
						<div class="col-md-8">
							<div class="clearfix">
								<div class="img">
									<img src="{{ reto.reto.materia.icon|thumbnail_url:'icon'}}" alt="{{ reto.reto.materia }}">
								</div>
								<h3 class="h2 pull-left m-0"><a href="{% url "reto_detail" id_reto=reto.reto.id%}">{{ reto.reto.materia }}</a></h3>
								<span class="date pull-right"><i class="fa fa-calendar"></i> {{ reto.reto.fecha }} </span>
							</div>

							<div class="description">
								<!-- Datos reto -->
								<div class="youplay-review-rating">
									<div class="row">
										<div class="col-md-8">
											<h3 class="mt-0">Notas de este reto</h3>
											<ul>
												{% for nota in reto.nota_list|dictsortreversed:"get_nota" %}
												<li><i class="fa fa-plus-circle"></i> {{ nota.alumno.nombre }} {{ nota.alumno.apellido }} {{ nota.get_nota }}</li>
												{% endfor %}
											</ul>
										</div>
										<div class="col-md-4">
											<a href="{% url "reto_detail" id_reto=reto.reto.id %}" class="btn read-more pull-left">Ver reto</a>
										</div>
									</div>
								</div>
								<!-- /Datos reto -->
							</div>

						</div>
					</div>
				</div>
				<!-- /Bloque reto -->
				{% endfor %}

			</section>
			<!-- /Lista retos -->

		</div>
	</div>
</section>
{% endblock content %}

escuela/main/templates/reto/detail.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block content %}
<!-- Page Content -->
<div class="container">


	<div class="row">
		<div class="col-sm-3">

			<img class="img-circle img-responsive img-center" src="{% static "img/calendar.jpg" %}" width="50" height="50" alt="">
			<h4 align="center" >{{ reto.fecha }}</h4>

		</div>
		<div class="col-sm-3">

			<img class="img-circle img-responsive img-center" src="{% static "img/1.jpg" %}" width="50" height="50" alt="">
			<h4 align="center" >{{ reto.pt_1 }} puntos</h4>

		</div>
		<div class="col-sm-3">

			<img class="img-circle img-responsive img-center" src="{% static "img/2.jpg" %}" width="50" height="50" alt="">
			<h4 align="center" >{{ reto.pt_2 }} puntos</h4>

		</div>
		<div class="col-sm-3">

			<img class="img-circle img-responsive img-center" src="{% static "img/3.jpg" %}" width="50" height="50" alt="">
			<h4 align="center" >{{ reto.pt_3 }} puntos</h4>

		</div>
	</div>
	<!-- /.row -->

	<div class="dividir">

	</div>


	<div class="row">
		<div class="col-sm-8">
			<h1  align="center">Notas de este Reto</h1>
			<div>
				{% if reto.jugado %}
				<table class="table table-striped" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Lugar</th>
							<th>Foto</th>
							<th>Alumno</th>
							<th>Equipo</th>
							<th>Nota</th>
						</tr>
					</thead>
					<tbody>
						{% for nota in reto.notas.all|dictsortreversed:"nota" %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.foto|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
							</td>
							<td>{{ nota.alumno }}</td>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.equipo.logo|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
							</td>
							<td>
								{{ nota.nota }}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% else %}
				<table class="table table-striped" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Equipo</th>
							<th>Foto</th>
							<th>Alumno</th>
							<th>Tokens</th>
							<th>Apoyar</th>
						</tr>
					</thead>
					<tbody>
						{% for nota in reto.notas.all %}
						<tr>
							<form method="post" action="{% url 'apuesta_create' nota_id=nota.id %}">
								<td>
									<img class="img-circle img-responsive" src="{{ nota.alumno.equipo.logo|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
								</td>
								<td>
									<img class="img-circle img-responsive" src="{{ nota.alumno.foto|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
								</td>
								<td>{{ nota.alumno }}</td>
								<td>
									{% csrf_token %}
									{{ apuesta_form.tokens }}
								</td>
								<td>
									<input type="submit" value="Apoyar" class="btn btn-primary">
								</td>
							</form>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% endif %}
			</div>
		</div>

		<div class="col-sm-4">
			{% if reto.jugado %}
				<h1  class="colorV" align="center">Apoyos</h1>
				<table class="table">
					<thead>
						<tr>
							<th>Equipo</th>
							<th>Tokens</th>
							<th>Puntos</th>
						</tr>
					</thead>
					<tbody>
						{% for apuesta in apuesta_list %}
							<tr>
								<td>
									<img class="img-circle img-responsive" src="{{ apuesta.nota.alumno.equipo.logo|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
								</td>
								<td>{{ apuesta.tokens }}</td>
								<td>{{ apuesta.get_punteo }}</td>
							</tr>
						{% endfor %}
						<tr>
							<td><b>Total</b></td>
							<td>{{ reto.tokens_apostados }}</td>
							<td>{{ reto.get_punteo }}</td>
						</tr>
					</tbody>
				</table>
			{% else %}
				<h1  class="colorV" align="center">Tokens Disponibles: {{ user.perfil.tokens_activos }}<br>Apoyos</h1>
				<h1  class="colorV" align="center">Apoyos</h1>
				<table class="table">
					<thead>
						<tr>
							<th>Equipo</th>
							<th>Tokens</th>
							<th>Puntos</th>
						</tr>
					</thead>
					<tbody>
						{% for apuesta in apuesta_list %}
							<tr>
								<td>
									<img class="img-circle img-responsive" src="{{ apuesta.nota.alumno.equipo.logo|thumbnail_url:"avatar-sm" }}" width="50" height="50" alt="">
								</td>
								<td>{{ apuesta.tokens }}</td>
								<td>{{ apuesta.get_punteo }}</td>
							</tr>
						{% endfor %}
						<tr>
							<td><b>Total</b></td>
							<td>{{ reto.tokens_apostados }}</td>
							<td>{{ reto.get_punteo }}</td>
						</tr>
					</tbody>
				</table>
			{% endif %}
		</div>
	</div>
</div>



{% endblock content %}


{% block javascript %}
{% if notificacion %}
<script>
	BootstrapDialog.alert('¡Apoyaste con éxito!');
</script>
{% endif %}
<script>
	$(document).ready(function () {
		var total_tokens = 0, total_puntos = 0;
		$.each($('.td-tokens'), function (index, td) {
			total_tokens += isNaN(parseInt($(td).html())) ? 0 : parseInt($(td).html());
		});
		$.each($('.td-puntos'), function (index, td) {
			total_puntos += isNaN(parseInt($(td).html())) ? 0 : parseInt($(td).html());
		});
		$('#total-tokens').html(total_tokens);
		$('#total-puntos').html(total_puntos);
	})
</script>
{% endblock javascript %}

escuela/main/templates/reto/list.html
{% extends "base/base.html" %}

{% load staticfiles thumbnail %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Retos a Jugarse
				<small>Listado</small>
			</h1>
		</div>
	</div>

	{% for reto in reto_list|dictsort:"fecha" %}
		{% if reto.jugado %}
		<div class="row">
			<h3>{{ reto.materia }}</h3>
			<h4><span class="glyphicon glyphicon-calendar"></span> {{ reto.fecha|date:"d/m/Y" }}</h4>
			<div class="col-md-7">
				<img class="img-circle img-responsive img-center" src="{{ reto.ganador.alumno.foto|thumbnail_url:'avatar' }}" width="300" height="300" alt="">
			</div>
			<div class="col-md-5">
				<h5>Notas de este reto</h5>
				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>Foto</th>
							<th>Nombre</th>
							<th>Equipo</th>
							<th>Punteo</th>
						</tr>
					</thead>
					<tbody>
						{% for nota in reto.notas.all|dictsortreversed:"nota" %}
						<tr>
							<th scope="row">{{ forloop.counter }}</th>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.foto|thumbnail_url:'avatar-sm' }}" width="25" height="25" alt="">
							</td>
							<td>{{ nota.alumno }}</td>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.equipo.logo|thumbnail_url:'avatar-sm' }}" width="25" height="25" alt="">
							</td>
							<td>{{ nota.nota }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<a class="btn btn-primary" href="{{ reto.get_absolute_url }}">Ver Reto <span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
		</div>
		{% else %}
		<div class="row">
			<h3>{{ reto.materia }}</h3>
			<h4><span class="glyphicon glyphicon-calendar"></span> {{ reto.fecha|date:"d/m/Y" }}</h4>
			<div class="col-md-7">
				<img class="img-circle img-responsive img-center" src="{% static "img/corazon200.jpg" %}" width="300" height="300" alt="">
			</div>
			<div class="col-md-5">
				<h6>Este reto aún no se juega</h6>
				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>Foto</th>
							<th>Nombre</th>
							<th>Equipo</th>
							<th>Punteo</th>
						</tr>
					</thead>
					<tbody>
						{% for nota in reto.notas.all %}
						<tr>
							<th scope="row"> - </th>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.foto|thumbnail_url:'avatar-sm' }}" width="25" height="25" alt="">
							</td>
							<td><a href="{{ nota.alumno.get_absolute_url }}">{{ nota.alumno }}</a></td>
							<td>
								<img class="img-circle img-responsive" src="{{ nota.alumno.equipo.logo|thumbnail_url:'avatar-sm' }}" width="25" height="25" alt="">
							</td>
							<td> - -</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<a class="btn btn-success" href="{{ reto.get_absolute_url }}">Apoyar <span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
		</div>
		{% endif %}
	{% endfor %}

{% endblock content %}

escuela/main/templates/reto/materia.html
{% extends "base/base.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<form action="" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<table class="table table-striped">
					{{ form.as_table }}
					<tr>
						<td colspan="2"><input type="submit" value="Guardar" class="btn btn-primary"></td>
					</tr>
				</table>
			</form>
		</div>
	</div>
</div>
{% endblock content %}